[build]
  command = "node scripts/write-env.mjs && npm run build -- --configuration production"
  publish = "dist/BrightFutureSchoolAngular/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
