services:
  - type: web
    name: bright-future-school
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: bright-future-school-db
          property: connectionString

databases:
  - name: bright-future-school-db
    plan: free
